### ISSUE TITLE
Leetcode 14. Longest common prefix java solution missing

### ISSUE THREAD

**Issue by okaydivyansh** [md-shamim-ahmad/LeetCode-Problem-Solution#101]
### Which problem do you want to solve?

I want to add java solution to the leetcode 14 Longest common prefix

### Input and Output details

The LeetCode problem "Longest Common Prefix" (problem number 14) asks you to find the longest common prefix among an array of strings. You are given an array of strings, and you need to find the longest string that is a prefix of all the strings in the array.

Here are the input and output details for this problem:

Input:

An array of strings, strs, where 0 <= strs.length <= 200 and 0 <= strs[i].length <= 200.
The input strings consist of only lowercase and uppercase English letters.
Output:

A string, which is the longest common prefix of all the strings in the input array strs.
If there is no common prefix among the input strings, return an empty string ("").

**Comment by okaydivyansh** [comment]
I have already created PR #100  for this issue which will close this issue @md-shamim-ahmad kindly add hacktoberfest label

**Comment by okaydivyansh** [comment]
@md-shamim-ahmad I have created PR #100 . Kindly merge

**Comment by md-shamim-ahmad** [comment]
Your solution code size is too long.

**Comment by okaydivyansh** [comment]
@md-shamim-ahmad committed the required changes
