### ISSUE TITLE
Add new solution in java for problem #21 Merge Two sorted LinkedLists

### ISSUE THREAD

**Issue by DEEPA-CHERI** [md-shamim-ahmad/LeetCode-Problem-Solution#117]
Which problem do you want to solve?
I want to add java solution to the leetcode [merge two sorted linkedlists](https://leetcode.com/problems/merge-two-sorted-lists/)

Input and Output details
You are given the heads of two sorted linked lists list1 and list2.
Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.
Return the head of the merged linked list.

Here are the input and output details for this problem:

Input: list1 = [1,2,4], list2 = [1,3,4]
Output: [1,1,2,3,4,4]

Additional Information
No response

**Comment by md-shamim-ahmad** [comment]
@DEEPA-CHERI please don't create an empty issue.
Provide details about the problem for the issue you created

**Comment by md-shamim-ahmad** [comment]
Hey @DEEPA-CHERI  if you have any plans to solve this question then you can solve it and create your PR.
