### ISSUE TITLE
Hacktoberfest 2023 (LeetCode-Problem-Solution)

### ISSUE THREAD

**Issue by md-shamim-ahmad** [md-shamim-ahmad/LeetCode-Problem-Solution#50]
### Welcome to Hacktoberfest 2023
Hello coders,

To get started on your journey in **Hacktoberfest 2023**, follow these steps:
* Register at [Hacktoberfest site](https://hacktoberfest.com/).
* Fork [LeetCode-Problem-Solution ](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/) to get a local copy as your workspace
* Learn how to make a perfect pull request ([guide](https://docs.github.com/en/desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request-from-github-desktop))
* You can open a [new issue](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/issues/new) mentioning the contribution you plan to make and open a pull request directly.
-----

### Some lists of problem to help you contribute:
* [Blind 75 LeetCode Questions Solution](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/Blind%2075%20LeetCode%20Questions%20Solution)
* [LeetCode Problems](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/LeetCode%20Problems)
* [SDE Interview Questions](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/SDE%20Interview%20Questions)
  * [Google](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/SDE%20Interview%20Questions/Google)
  * [Microsoft](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/SDE%20Interview%20Questions/Microsoft)
  * [Apple](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/SDE%20Interview%20Questions/Apple)
  * [American Express](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/SDE%20Interview%20Questions/American%20Express)
  * [Bloomberg](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/SDE%20Interview%20Questions/Bloomberg)
  * [Uber](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/SDE%20Interview%20Questions/Uber)
  * [Top Interview 150](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/SDE%20Interview%20Questions/Top%20Interview%20150)
  * [Yahoo](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/tree/main/SDE%20Interview%20Questions/Yahoo)
  * etc.
----------------

### Quick hints:
* The sign ```❌``` indicates that there have no solution code for this problem into this repository. So you can create PR(```pull request```) for these problem.
* The sign ```✔️``` indicates that there have an existing solution code for this problem into this repository.
But If your proposed code is better than the existing code in terms of **```code size```** or **```time or space complexity ```**, then you can also create a PR and I will merge the PR.
----------------------

**Have a doubt or want me to review your contribution? Ask me down 👇 and I try to will help you InshaAllah.**

**Comment by whitebeard10** [comment]
@md-shamim-ahmad

can you add `hacktoberfest-accepted` label too as this  was mentioned in officinal site for hacktoberfest

**Comment by md-shamim-ahmad** [comment]
@whitebeard10 
Yes I know but I thought that the **```hacktoberfest2023```** label was enough.
Thanks for your comment.
I will create  **```hacktoberfest-accepted```** label.

**Comment by whitebeard10** [comment]
@md-shamim-ahmad  also can you assign me for this issue so i can start contributing ?

**Comment by md-shamim-ahmad** [comment]
@whitebeard10 hey feel free to create **PR**. I will merge your **PR** if the code is correct.

**Comment by ankitmwd01** [comment]
Assign me this task.

**Comment by sammyifelse** [comment]
plz assign me this task

**Comment by roushan-rks** [comment]
Please assign me this task @md-shamim-ahmad

**Comment by urvashi-2004** [comment]
@md-shamim-ahmad I'd like to do this. Please assign this to me.

**Comment by md-shamim-ahmad** [comment]
@ankitmwd01, @sammyifelse, @roushan-rks Do you peoples have any plan to solve this problem?
