### ISSUE TITLE
add solution for "four sum"

### ISSUE THREAD

**Issue by md-shamim-ahmad** [md-shamim-ahmad/LeetCode-Problem-Solution#65]
**Added your solution code for this problem**
**Added your solution code for this problem**
--------

**original question link [here](https://leetcode.com/problems/4sum/description/)**

<div class="elfjS" data-track-load="description_content"><p>Given an array <code>nums</code> of <code>n</code> integers, return <em>an array of all the <strong>unique</strong> quadruplets</em> <code>[nums[a], nums[b], nums[c], nums[d]]</code> such that:</p>

<ul>
	<li><code>0 &lt;= a, b, c, d&nbsp;&lt; n</code></li>
	<li><code>a</code>, <code>b</code>, <code>c</code>, and <code>d</code> are <strong>distinct</strong>.</li>
	<li><code>nums[a] + nums[b] + nums[c] + nums[d] == target</code></li>
</ul>

<p>You may return the answer in <strong>any order</strong>.</p>

<p>&nbsp;</p>
<p><strong class="example">Example 1:</strong></p>

<pre><strong>Input:</strong> nums = [1,0,-1,0,-2,2], target = 0
<strong>Output:</strong> [[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]
</pre>

<p><strong class="example">Example 2:</strong></p>

<pre><strong>Input:</strong> nums = [2,2,2,2,2], target = 8
<strong>Output:</strong> [[2,2,2,2]]
</pre>

<p>&nbsp;</p>
<p><strong>Constraints:</strong></p>

<ul>
	<li><code>1 &lt;= nums.length &lt;= 200</code></li>
	<li><code>-10<sup>9</sup> &lt;= nums[i] &lt;= 10<sup>9</sup></code></li>
	<li><code>-10<sup>9</sup> &lt;= target &lt;= 10<sup>9</sup></code></li>
</ul>
</div>

**Comment by SaiganeshGurrapu16** [comment]
hey, @md-shamim-ahmad can you assign me? I will solve it in C++.

**Comment by md-shamim-ahmad** [comment]
Feel free to create pull request for this problem

**Comment by SaiganeshGurrapu16** [comment]
Can you assign me

**Comment by md-shamim-ahmad** [comment]
This problem already solve by java language #83

**Comment by md-shamim-ahmad** [comment]
If you want to solve in other language except Java, you can do it

**Comment by sammyifelse** [comment]
can i solve this in python

**Comment by md-shamim-ahmad** [comment]
@sammyifelse Of Course, Why Not?
