### ISSUE TITLE
Add solution Q41. First missing positive

### ISSUE THREAD

**Issue by vivekrawat21** [md-shamim-ahmad/LeetCode-Problem-Solution#78]

**Comment by vivekrawat21** [comment]
assign me this

**Comment by vivekrawat21** [comment]
assign me this

**Comment by vivekrawat21** [comment]
@md-shamim-ahmad i have created a pr regarding this issue can you please assign me this and then check the pr

**Comment by vivekrawat21** [comment]
And please give label hacktoberfest accepted as it is mentioned in the site

**Comment by sammyifelse** [comment]
please assign this issue to me

**Comment by md-shamim-ahmad** [comment]
Feel free to create your PR

**Comment by urvashi-2004** [comment]
I'd like to do this project. You can assign this to me.

**Comment by urvashi-2004** [comment]
I'd like to do this. You can assign this to me.

**Comment by md-shamim-ahmad** [comment]
> I'd like to do this. You can assign this to me.

@urvashi-2004 
In which language do you want to solve it?
And what would be the complexity of your proposed solution code?

**Comment by md-shamim-ahmad** [comment]
> please assign this issue to me

@sammyifelse 
In which language do you want to solve it?
And what would be the complexity of your proposed solution code?

**Comment by urvashi-2004** [comment]
> > I'd like to do this. You can assign this to me.
> 
> @urvashi-2004 In which language do you want to solve it? And what would be the complexity of your proposed solution code?

I would like to solve this problem in c++ in o(n) time complexity

**Comment by urvashi-2004** [comment]
@md-shamim-ahmad I have created a PR regarding this issue. Please let me know if anything else left.

**Comment by urvashi-2004** [comment]
Hey,
I have solved this issue and created the PR regarding this issue. Please review my code and let me know if anything is wrong.
