### ISSUE TITLE
Leetcode 13. Roman to Integer in java lang is missing

### ISSUE THREAD

**Issue by okaydivyansh** [md-shamim-ahmad/LeetCode-Problem-Solution#96]
### Which problem do you want to solve?

Can i add java solution of 13. Roman to Integer in Leetcode repo

### Input and Output details

The "Roman to Integer" problem on LeetCode involves converting a Roman numeral string to an integer. Here are the input and output details for this problem:

Problem Statement:

Given a Roman numeral as input, you need to write a function to convert it to an integer.

Roman numerals are represented by seven different symbols:

I (1)
V (5)
X (10)
L (50)
C (100)
D (500)
M (1000)
For example, the Roman numeral "III" is represented as 3, "IV" as 4, "IX" as 9, "LVIII" as 58, and "MCMXCIV" as 1994.
Input:

s (1 <= s.len<= 15): A Roman numeral string.
Output:

An integer representing the converted value of the Roman numeral.

**Comment by md-shamim-ahmad** [comment]
Feel free to create your PR
